---
application:
  name: "buildspecial"
  project: "hust_special"
  organization: "QoveryCommunity"
routers:
- name: "main-buildspecial"
  routes:
  - application_name: "buildspecial"
    paths:
    - "/*"
